name: Actions workflow
on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Sample github action
        id: greeting
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: Hemalatha
      - name: Log greeting time
        run: echo "${{steps.greeting.outputs.time}}"


